import './globals.css'
import Navbar from '../components/navbar'
import { SessionProvider } from '../lib/providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <SessionProvider>

      <body>
        <Navbar />
        {children}
        <Navbar />
      </body>
      </SessionProvider>
    </html>
  )
}
